export const candidateData = [
    {
      "Candidate": "rachel@jumpstart-uk.com",
      "Candidate Full Name": "Rachel Howe",
      "Raw CV (from Candidate)": "https://drive.google.com/file/d/1sw05wh0hDU6ZsxfyI22zQRp_AtWu96bW/view?usp=drive_link",
      "Jumpstart selection stream": "Generalist",
      "Right to Work": "Yes - British Passport",
      "LinkedIn RAW (from Candidate)": "https://www.linkedin.com/in/rachel-howe-1504b61b2/",
      "Undergrad degree type (from Candidate)": "BA",
      "Undergrad subject (from Candidate)": "Music",
      "Undergrad university (from Candidate)": "Oxford University",
      "Undergrad graduation year (from Candidate)": 2021,
      "Undergrad result (from Candidate)": "1st Class",
      "CV RAW (from Candidate)": "https://drive.google.com/file/d/1sw05wh0hDU6ZsxfyI22zQRp_AtWu96bW/view?usp=drive_link",
      "Photo (from Candidate)": null,
      "Github RAW (from Candidate)": "N/A",
      "(1) Work Experience Role (from Candidate)": "Programme & Strategy Lead",
      "(1) Work Experience Company (from Candidate)": "Jumpstart",
      "(1) Work Experience Description (from Candidate)": "Leading programme and strategy initiatives.",
      "(1) Time spent in work experience (from Candidate)": "2yrs",
      "(2) Work Experience Company (from Candidate)": "Oxford Lieder",
      "(2) Work Experience Role (from Candidate)": "Events & Marketing",
      "(2) Work Experience Description (from Candidate)": "Executed marketing strategies for events.",
      "(2) Time spent in work experience (from Candidate)": "1yr",
      "Coding languages new (from Candidate)": "N/A",
      "Top achievement (from Candidate)": "Classically trained singer with international performance experience.",
      "Languages (from Candidate)": "Spanish, Arabic, French",
      "Generalist roles suitable for copy (from Candidate)": "Founder Associate, Operations",
      "Preferred working style copy (from Candidate)": "Hybrid (1-4 days in office) or 5 days a week in office",
      "Minimum salary (from Candidate)": "£45k",
      "Ideal salary (from Candidate)": "£55k",
      "Raw video intro (from Candidate)": "https://share.vidyard.com/watch/ntKamdybDKetSjWFACUUEV?autoplay=1",
      "Role applied for": "Founder's Associate",
      "Ranking": "Not ranked",
      "Match type": "Application",
      "Application Rationale": "As a proactive problem-solver with a track record of excelling in fast-paced environments, I thrive on wearing multiple hats to support ambitious goals. I bring sharp analytical skills, strategic thinking, and a hands-on approach to executing key projects. My experience in streamlining processes, managing stakeholders, and driving growth aligns with the dynamic needs of a Founder's Associate role. I'm excited to collaborate directly with founders, turning ideas into impactful outcomes and ensuring operational excellence.",
      "Stage": "Interviewing",
      "Stage last modified": "09/12/2024",
      "Notes": null
    },
    {
      "Candidate": "alex@gmail.com",
      "Candidate Full Name": "Alex Carter",
      "Raw CV (from Candidate)": "https://drive.google.com/file/d/1example_CV1/view?usp=drive_link",
      "Jumpstart selection stream": "Generalist",
      "Right to Work": "Yes - Settled Status",
      "LinkedIn RAW (from Candidate)": "https://www.linkedin.com/in/alex-carter-2345/",
      "Undergrad degree type (from Candidate)": "BSc",
      "Undergrad subject (from Candidate)": "Computer Science",
      "Undergrad university (from Candidate)": "University of Cambridge",
      "Undergrad graduation year (from Candidate)": 2020,
      "Undergrad result (from Candidate)": "2:1",
      "CV RAW (from Candidate)": "https://drive.google.com/file/d/1example_CV1/view?usp=drive_link",
      "Photo (from Candidate)": null,
      "Github RAW (from Candidate)": "https://github.com/alexcarter",
      "(1) Work Experience Role (from Candidate)": "Software Constulant",
      "(1) Work Experience Company (from Candidate)": "Google",
      "(1) Work Experience Description (from Candidate)": "Developed scalable web solutions.",
      "(1) Time spent in work experience (from Candidate)": "3yrs",
      "(2) Work Experience Company (from Candidate)": "Microsoft",
      "(2) Work Experience Role (from Candidate)": "Software Development Intern",
      "(2) Work Experience Description (from Candidate)": "Built internal tools for team collaboration.",
      "(2) Time spent in work experience (from Candidate)": "1yr",
      "Coding languages new (from Candidate)": "Java",
      "Top achievement (from Candidate)": "Developed an AI-based chatbot for customer service.",
      "Languages (from Candidate)": "N/A",
      "Generalist roles suitable for copy (from Candidate)": "Founder Associate, Product",
      "Preferred working style copy (from Candidate)": "Remote or Hybrid",
      "Minimum salary (from Candidate)": "£50k",
      "Ideal salary (from Candidate)": "£60k",
      "Raw video intro (from Candidate)": "https://share.vidyard.com/watch/example1?autoplay=1",
      "Role applied for": "Founder's Associate",
      "Ranking": "Not ranked",
      "Match type": "Application",
      "Application Rationale": "With a proven ability to adapt and deliver in high-pressure environments, I excel at juggling multiple responsibilities to achieve ambitious targets. My blend of analytical thinking, strategic insight, and hands-on execution enables me to tackle complex challenges and drive meaningful results. Having honed my skills in optimizing processes and fostering collaboration, I'm eager to partner with founders to transform ideas into impactful projects and contribute to the success of a dynamic organization",
      "Stage": "Interviewing",
      "Stage last modified": "06/12/2024",
      "Notes": null
    },
    {
      "Candidate": "sophie@gmail.com",
      "Candidate Full Name": "Sophie Green",
      "Raw CV (from Candidate)": "https://drive.google.com/file/d/1example_CV2/view?usp=drive_link",
      "Jumpstart selection stream": "Generalist",
      "Right to Work": "Yes - British Passport",
      "LinkedIn RAW (from Candidate)": "https://www.linkedin.com/in/sophie-green-6789/",
      "Undergrad degree type (from Candidate)": "BA",
      "Undergrad subject (from Candidate)": "Business Management",
      "Undergrad university (from Candidate)": "University of Manchester",
      "Undergrad graduation year (from Candidate)": 2022,
      "Undergrad result (from Candidate)": "1st Class",
      "CV RAW (from Candidate)": "https://drive.google.com/file/d/1example_CV2/view?usp=drive_link",
      "Photo (from Candidate)": null,
      "Github RAW (from Candidate)": "N/A",
      "(1) Work Experience Role (from Candidate)": "Sales Associate",
      "(1) Work Experience Company (from Candidate)": "Amazon",
      "(1) Work Experience Description (from Candidate)": "Drove customer acquisition strategies.",
      "(1) Time spent in work experience (from Candidate)": "2yrs",
      "(2) Work Experience Company (from Candidate)": "Deloitte",
      "(2) Work Experience Role (from Candidate)": "Business Consultant",
      "(2) Work Experience Description (from Candidate)": "Analyzed market trends to improve client outcomes.",
      "(2) Time spent in work experience (from Candidate)": "1yr",
      "Coding languages new (from Candidate)": "N/A",
      "Top achievement (from Candidate)": "Led a team to increase regional sales by 20%.",
      "Languages (from Candidate)": "French",
      "Generalist roles suitable for copy (from Candidate)": "Product, Operations",
      "Preferred working style copy (from Candidate)": "5 days a week in office",
      "Minimum salary (from Candidate)": "£40k",
      "Ideal salary (from Candidate)": "£50k",
      "Raw video intro (from Candidate)": "https://share.vidyard.com/watch/example2?autoplay=1",
      "Role applied for": "Founder's Associate",
      "Ranking": "Not ranked",
      "Match type": "Application",
      "Application Rationale": "I thrive in environments that demand adaptability, problem-solving, and a focus on delivering results. My background in managing diverse projects, streamlining operations, and building strong stakeholder relationships equips me to navigate the dynamic challenges of a Founder's Associate role. By combining strategic vision with a practical, action-oriented mindset, I aim to support founders in driving growth, overcoming obstacles, and turning bold ideas into measurable success.",
      "Stage": "Interviewing",
      "Stage last modified": "10/12/2024",
      "Notes": null
    },
    {
      "Candidate": "james@gmail.com",
      "Candidate Full Name": "James Lee",
      "Raw CV (from Candidate)": "https://drive.google.com/file/d/1example_CV3/view?usp=drive_link",
      "Jumpstart selection stream": "Generalist",
      "Right to Work": "Yes - British Passport",
      "LinkedIn RAW (from Candidate)": "https://www.linkedin.com/in/james-lee-9876/",
      "Undergrad degree type (from Candidate)": "MSc",
      "Undergrad subject (from Candidate)": "Marketing and Strategy",
      "Undergrad university (from Candidate)": "London School of Economics",
      "Undergrad graduation year (from Candidate)": 2021,
      "Undergrad result (from Candidate)": "Distinction",
      "CV RAW (from Candidate)": "https://drive.google.com/file/d/1example_CV3/view?usp=drive_link",
      "Photo (from Candidate)": null,
      "Github RAW (from Candidate)": "https://github.com/jameslee",
      "(1) Work Experience Role (from Candidate)": "Marketing Manager",
      "(1) Work Experience Company (from Candidate)": "Spotify",
      "(1) Work Experience Description (from Candidate)": "Led global campaigns for brand partnerships.",
      "(1) Time spent in work experience (from Candidate)": "3yrs",
      "(2) Work Experience Company (from Candidate)": "Uber",
      "(2) Work Experience Role (from Candidate)": "Social Media Specialist",
      "(2) Work Experience Description (from Candidate)": "Managed multi-platform campaigns and analytics.",
      "(2) Time spent in work experience (from Candidate)": "2yrs",
      "Coding languages new (from Candidate)": "N/A",
      "Top achievement (from Candidate)": "Published a whitepaper on digital marketing trends.",
      "Languages (from Candidate)": "German",
      "Generalist roles suitable for copy (from Candidate)": "Founder Associate, Customer Success",
      "Preferred working style copy (from Candidate)": "Hybrid",
      "Minimum salary (from Candidate)": "£55k",
      "Ideal salary (from Candidate)": "£65k",
      "Raw video intro (from Candidate)": "https://share.vidyard.com/watch/example3?autoplay=1",
      "Role applied for": "Founder's Associate",
      "Ranking": "Not ranked",
      "Match type": "Application",
      "Application Rationale": "As a versatile and results-driven professional, I bring a unique combination of critical thinking, operational expertise, and a passion for driving progress in high-growth settings. My experience spans process improvement, stakeholder management, and delivering strategic initiatives. I'm motivated by the opportunity to work closely with founders, ensuring smooth execution and impactful outcomes while contributing to the broader goals of an innovative team.",
      "Stage": "Interviewing",
      "Stage last modified": "09/12/2024",
      "Notes": null
    },
{
    "Candidate": "mme014@alumni.bham.ac.uk",
    "Candidate Full Name": "Mohamed Elsayed",
    "Raw CV (from Candidate)": "https://drive.google.com/file/d/1example_CV3/view?usp=drive_link",
    "Jumpstart selection stream": "Software engineering",
    "Right to Work": "Yes - Grad visa",
    "LinkedIn RAW (from Candidate)": "https://www.linkedin.com/in/mohamed-elsayed285/",
    "Undergrad degree type (from Candidate)": "Bsc",
    "Undergrad subject (from Candidate)": "Computer science",
    "Undergrad university (from Candidate)": "University of Birmingham",
    "Undergrad graduation year (from Candidate)": 2024,
    "Undergrad result (from Candidate)": "Distinction",
    "CV RAW (from Candidate)": "https://aw.valyfy.com/v1/storage/buckets/resumes/files/6753952f0011c2625da1/view?project=jigsaw-web-client1",
    "Photo (from Candidate)": null,
    "Github RAW (from Candidate)": "https://github.com/momo285",
    "(1) Work Experience Role (from Candidate)": "Tech Lead",
    "(1) Work Experience Company (from Candidate)": "Valyfy",
    "(1) Work Experience Description (from Candidate)": "Led the development of a marketplace platform connected students to startups",
    "(1) Time spent in work experience (from Candidate)": "1yrs",
    "(2) Work Experience Company (from Candidate)": "New Hawai for tourism and investment",
    "(2) Work Experience Role (from Candidate)": "Flutter Mobile Developer",
    "(2) Work Experience Description (from Candidate)": "Developed a full stack Mobile application for theme park company",
    "(2) Time spent in work experience (from Candidate)": "1yrs",
    "Coding languages new (from Candidate)": "Javascript , Typescript , HTML , C++",
    "Top achievement (from Candidate)": "Delivered an hour-long talk on GenAI to 30+ second-year apprenticeship students at Northeastern University London,",
    "Languages (from Candidate)": "English , Arabic",
    "Generalist roles suitable for copy (from Candidate)": "Software engineering",
    "Preferred working style copy (from Candidate)": "Hybrid",
    "Minimum salary (from Candidate)": "£40k",
    "Ideal salary (from Candidate)": "£60k",
    "Raw video intro (from Candidate)": "https://share.vidyard.com/watch/example3?autoplay=1",
    "Role applied for": "Software engineering",
    "Ranking": "Not ranked",
    "Match type": "Application",
    "Application Rationale": "As a versatile and results-driven professional, I bring a unique combination of critical thinking, operational expertise, and a passion for driving progress in high-growth settings. My experience spans process improvement, stakeholder management, and delivering strategic initiatives. I'm motivated by the opportunity to work closely with founders, ensuring smooth execution and impactful outcomes while contributing to the broader goals of an innovative team.",
    "Stage": "Interviewing",
    "Stage last modified": "09/12/2024",
    "Notes": null
}
];
