// src/mockData.js

export const mockCandidates = [
    {
      "Candidate": "john.doe@gmail.com",
      "Candidate Full Name": "John Doe",
      "Raw CV (from Candidate)": "https://example.com/cv.pdf",
      "Jumpstart selection stream": "Engineering",
      "Right to Work": "Yes",
      "LinkedIn RAW (from Candidate)": "https://linkedin.com/in/johndoe",
      "Undergrad degree type (from Candidate)": "Bachelor of Science",
      "Undergrad subject (from Candidate)": "Computer Science",
      "Undergrad university (from Candidate)": "Imperial College London",
      "Undergrad graduation year (from Candidate)": 2022,
      "Undergrad result (from Candidate)": "First Class Honours",
      "CV RAW (from Candidate)": "https://example.com/cv_raw.pdf",
      "Photo (from Candidate)": "/placeholder.jpg",
      "Github RAW (from Candidate)": "https://github.com/johndoe",
      "(1) Work Experience Role (from Candidate)": "Software Engineer",
      "(1) Work Experience Company (from Candidate)": "Google",
      "(1) Work Experience Description (from Candidate)": "Led development of key features for Google Cloud Platform, focusing on scalability and performance optimization. Implemented microservices architecture that improved system response time by 40%.",
      "(1) Time spent in work experience (from Candidate)": "2 years",
      "(2) Work Experience Company (from Candidate)": "Meta",
      "(2) Work Experience Role (from Candidate)": "Frontend Developer",
      "(2) Work Experience Description (from Candidate)": "Developed and maintained user-facing features for Facebook Marketplace. Improved page load times by 25% through optimization techniques.",
      "(2) Time spent in work experience (from Candidate)": "1.5 years",
      "Coding languages new (from Candidate)": "Python, JavaScript, TypeScript, React, Node.js, Java",
      "Top achievement (from Candidate)": "Led a team of 5 engineers to deliver a major platform migration project ahead of schedule, resulting in 30% improved performance",
      "Languages (from Candidate)": "English (Native), Spanish (Fluent), French (Basic)",
      "Generalist roles suitable for copy (from Candidate)": "Software Engineering, Full Stack Development, Technical Lead",
      "Preferred working style copy (from Candidate)": "Remote",
      "Minimum salary (from Candidate)": "£65,000",
      "Ideal salary (from Candidate)": "£85,000",
      "Raw video intro (from Candidate)": "https://example.com/video.mp4",
      "Role applied for": "Senior Software Engineer",
      "Ranking": "A+",
      "Match type": "High Match",
      "Application Rationale": "I am passionate about building scalable systems and have extensive experience in cloud technologies. I believe my background in both frontend and backend development makes me an ideal candidate for this role.",
      "Stage": "INTERVIEW",
      "Stage last modified": "2024-03-15T14:30:00Z",
      "Notes": [
        "Excellent communication skills shown in initial screening",
        "Strong technical background",
        "Good cultural fit"
      ]
    },
    {
      "Candidate": "jane.smith@gmail.com",
      "Candidate Full Name": "Jane Smith",
      "Raw CV (from Candidate)": "https://example.com/jane_cv.pdf",
      "Jumpstart selection stream": "Product",
      "Right to Work": "Yes",
      "LinkedIn RAW (from Candidate)": "https://linkedin.com/in/janesmith",
      "Undergrad degree type (from Candidate)": "Master of Science",
      "Undergrad subject (from Candidate)": "Product Design",
      "Undergrad university (from Candidate)": "UCL",
      "Undergrad graduation year (from Candidate)": 2021,
      "Undergrad result (from Candidate)": "Distinction",
      "CV RAW (from Candidate)": "https://example.com/jane_cv_raw.pdf",
      "Photo (from Candidate)": "/placeholder2.jpg",
      "Github RAW (from Candidate)": "https://github.com/janesmith",
      "(1) Work Experience Role (from Candidate)": "Product Manager",
      "(1) Work Experience Company (from Candidate)": "Spotify",
      "(1) Work Experience Description (from Candidate)": "Led product strategy for Spotify's podcast platform. Launched 3 major features that increased user engagement by 45%.",
      "(1) Time spent in work experience (from Candidate)": "2.5 years",
      "(2) Work Experience Company (from Candidate)": "Apple",
      "(2) Work Experience Role (from Candidate)": "UX Designer",
      "(2) Work Experience Description (from Candidate)": "Designed user interfaces for Apple Music, contributing to a 20% improvement in user satisfaction scores.",
      "(2) Time spent in work experience (from Candidate)": "1 year",
      "Coding languages new (from Candidate)": "HTML, CSS, JavaScript, Figma, Sketch",
      "Top achievement (from Candidate)": "Successfully led the redesign of Spotify's podcast discovery experience, resulting in a 60% increase in podcast listeners",
      "Languages (from Candidate)": "English (Native), German (Fluent)",
      "Generalist roles suitable for copy (from Candidate)": "Product Management, UX Design, Product Strategy",
      "Preferred working style copy (from Candidate)": "Hybrid",
      "Minimum salary (from Candidate)": "£75,000",
      "Ideal salary (from Candidate)": "£95,000",
      "Raw video intro (from Candidate)": "https://example.com/jane_video.mp4",
      "Role applied for": "Senior Product Manager",
      "Ranking": "A",
      "Match type": "High Match",
      "Application Rationale": "With my background in both product management and UX design, I bring a unique perspective to product development. I'm particularly excited about the opportunity to work on innovative features that impact millions of users.",
      "Stage": "OFFER",
      "Stage last modified": "2024-03-14T10:15:00Z",
      "Notes": [
        "Strong product vision",
        "Excellent stakeholder management skills",
        "Great cultural alignment"
      ]
    }
  ];
  
  export const stages = [
    { id: "NEW APPLICATION", title: "New Application" },
    { id: "HR REVIEW", title: "HR Review" },
    { id: "INTERVIEW", title: "Interview" },
    { id: "OFFER", title: "Offer" },
    { id: "HIRED", title: "Hired" },
    { id: "ARCHIVED", title: "Archived" }
  ];